{
 "title": "Meteo Backend Dashboard",
 "panels": [
  {
   "title": "Total HTTP Requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "rate(django_http_requests_total_by_method_total[1m])",
     "legendFormat": "{{method}} - {{view}}"
    }
   ]
  },
  {
   "title": "HTTP Response Status",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "rate(django_http_responses_total_by_status_total[1m])",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Python Process CPU User Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "rate(python_info_cpu_time_seconds_total[1m])",
     "legendFormat": "CPU Time"
    }
   ]
  },
  {
   "title": "Python Process Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    { "expr": "python_info_memory_rss_bytes", "legendFormat": "RSS Memory" }
   ]
  }
 ]
}